/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.torredelrey.gestorfacturas.vista;

import es.torredelrey.gestorfacturas.controlador.UsuarioJpaController;
import es.torredelrey.gestorfacturas.modelo.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Locale;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Usuario
 */
public class LogIn extends javax.swing.JFrame {
    
    private EntityManagerFactory emf;
    private UsuarioJpaController ujc;
    
    public LogIn() {
        setLookAndFeel("Nimbus");
        
        ///////////////IDIOMA////////////////************************************
        Locale.setDefault(Locale.getDefault()); //UK para inglés
        /////////////////////////////////////************************************
        
        initComponents();
        
        //BD
        emf = Persistence.createEntityManagerFactory("persistence");
        ujc = new UsuarioJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        txfContrasena = new javax.swing.JTextField();
        lblRestablecer = new javax.swing.JLabel();
        lblNoCuenta = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/torredelrey/gestorfacturas/vista/Bundle"); // NOI18N
        lblUsuario.setText(bundle.getString("LogIn.lblUsuario.text")); // NOI18N

        lblContrasena.setForeground(new java.awt.Color(102, 102, 102));
        lblContrasena.setText(bundle.getString("LogIn.lblContrasena.text")); // NOI18N

        txfUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfUsuarioFocusGained(evt);
            }
        });
        txfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsuarioActionPerformed(evt);
            }
        });

        txfContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfContrasenaFocusGained(evt);
            }
        });

        lblRestablecer.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        lblRestablecer.setForeground(new java.awt.Color(0, 51, 102));
        lblRestablecer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestablecer.setText(bundle.getString("LogIn.lblRestablecer.text")); // NOI18N
        lblRestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRestablecerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRestablecerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRestablecerMouseExited(evt);
            }
        });

        lblNoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        lblNoCuenta.setText(bundle.getString("LogIn.lblNoCuenta.text")); // NOI18N

        btnLogin.setBackground(new java.awt.Color(0, 102, 204));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText(bundle.getString("LogIn.btnLogin.text")); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setText(bundle.getString("LogIn.btnRegistrar.text")); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText(bundle.getString("LogIn.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText(bundle.getString("LogIn.lblTitulo.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfContrasena)
                    .addComponent(lblContrasena)
                    .addComponent(lblUsuario)
                    .addComponent(txfUsuario)
                    .addComponent(lblRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestablecer)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lblNoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar)
                .addGap(77, 77, 77)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static void setLookAndFeel(String lookAndFeelName) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (lookAndFeelName.equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        boolean salir = false;
        if(txfUsuario.getText().isBlank() || txfUsuario.getText().isEmpty() || txfUsuario.getForeground()==Color.red){
            salir=true;
            txfUsuario.setForeground(Color.red);
            txfUsuario.setText("Introduce un usuario");
        }
        
        if(txfContrasena.getText().isBlank() || txfContrasena.getText().isEmpty() || txfContrasena.getForeground()==Color.red){
            salir=true;
            txfContrasena.setForeground(Color.red);
            txfContrasena.setText("Introduce una contraseña");
        }
        
        if(salir) return;
        
        ArrayList<Usuario> usuarios = new ArrayList<>(ujc.findUsuarioEntities());
        for(Usuario u : usuarios){
            if(u.getUsuario().equals(txfUsuario.getText())){
                if(u.getPassword().equals(txfContrasena.getText())){
                    Menu m = new Menu();
                    m.setDefaultCloseOperation(EXIT_ON_CLOSE);
                    m.show(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this,"Contraseña incorrecta");
                }
                return;
            }
        }

        JOptionPane.showMessageDialog(this,"Ese usuario no existe");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsuarioActionPerformed

    private void txfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUsuarioFocusGained
        if(txfUsuario.getForeground()==Color.red){
            Color og = new Color(51,51,51);
            txfUsuario.setForeground(og);
            txfUsuario.setText("");
        }
    }//GEN-LAST:event_txfUsuarioFocusGained

    private void txfContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfContrasenaFocusGained
        if(txfContrasena.getForeground()==Color.red){
            Color og = new Color(51,51,51);
            txfContrasena.setForeground(og);
            txfContrasena.setText("");
        }
    }//GEN-LAST:event_txfContrasenaFocusGained

    private void lblRestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerMouseClicked
        RestablecerContrasena rc = new RestablecerContrasena();
        rc.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rc.show(true);
    }//GEN-LAST:event_lblRestablecerMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        RegistrarCuenta rc = new RegistrarCuenta();
        rc.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rc.show(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lblRestablecerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerMouseEntered
        Color c = new Color(0, 232, 255);
        lblRestablecer.setForeground(c);
    }//GEN-LAST:event_lblRestablecerMouseEntered

    private void lblRestablecerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestablecerMouseExited
        Color c = new Color(0,51,102);
        lblRestablecer.setForeground(c);
    }//GEN-LAST:event_lblRestablecerMouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNoCuenta;
    private javax.swing.JLabel lblRestablecer;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txfContrasena;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
