/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.torredelrey.gestorfacturas.vista;

import es.torredelrey.gestorfacturas.controlador.UsuarioJpaController;
import es.torredelrey.gestorfacturas.modelo.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RestablecerContrasena extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private UsuarioJpaController ujc;
    
    public RestablecerContrasena() {
        initComponents();
        
        setTitle("Restablecer contraseña");
        
        //BD
        emf = Persistence.createEntityManagerFactory("persistence");
        ujc = new UsuarioJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txfContrasena1 = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena1 = new javax.swing.JLabel();
        txfContrasena2 = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfUsuarioFocusGained(evt);
            }
        });

        lblContrasena.setForeground(new java.awt.Color(102, 102, 102));
        lblContrasena.setText("Contraseña");

        txfContrasena1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfContrasena1FocusGained(evt);
            }
        });

        btnCrearCuenta.setBackground(new java.awt.Color(0, 102, 204));
        btnCrearCuenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Guardar contraseña");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("Usuario");

        lblContrasena1.setForeground(new java.awt.Color(102, 102, 102));
        lblContrasena1.setText("Repetir contraseña");

        txfContrasena2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfContrasena2FocusGained(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setForeground(new java.awt.Color(102, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContrasena1)
                            .addComponent(lblContrasena)
                            .addComponent(lblUsuario)
                            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txfContrasena1)
                            .addComponent(txfUsuario)
                            .addComponent(txfContrasena2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasena1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        boolean salir = false;
        if(txfUsuario.getText().isBlank() || txfUsuario.getText().isEmpty() || txfUsuario.getForeground()==Color.red){
            salir=true;
            txfUsuario.setForeground(Color.red);
            txfUsuario.setText("Introduce un usuario");
        }
        
        if(txfContrasena1.getText().isBlank() || txfContrasena1.getText().isEmpty() || txfContrasena1.getForeground()==Color.red){
            salir=true;
            txfContrasena1.setForeground(Color.red);
            txfContrasena1.setText("Introduce una contraseña");
        }
        
        if(!txfContrasena1.getText().equals(txfContrasena2.getText()) || txfContrasena2.getForeground()==Color.red){
            salir=true;
            txfContrasena2.setForeground(Color.red);
            txfContrasena2.setText("Las contraseñas deben ser iguales");
        }
        
        if(salir) return;
        
        ArrayList<Usuario> usuarios = new ArrayList<>(ujc.findUsuarioEntities());
        for(Usuario u : usuarios){
            if(u.getUsuario().equals(txfUsuario.getText())){
                u.setPassword(txfContrasena1.getText());
                try {
                    ujc.edit(u);
                } catch (Exception ex) {
                    Logger.getLogger(RestablecerContrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this,"Contraseña cambiada con éxito");
                this.dispose();
                return;
            }
        }

        JOptionPane.showMessageDialog(this,"Ese usuario no existe");
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void txfContrasena1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfContrasena1FocusGained
        if(txfContrasena1.getForeground()==Color.red){
            Color og = new Color(51,51,51);
            txfContrasena1.setForeground(og);
            txfContrasena1.setText("");
        }
    }//GEN-LAST:event_txfContrasena1FocusGained

    private void txfContrasena2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfContrasena2FocusGained
        if(txfContrasena2.getForeground()==Color.red){
            Color og = new Color(51,51,51);
            txfContrasena2.setForeground(og);
            txfContrasena2.setText("");
        }
    }//GEN-LAST:event_txfContrasena2FocusGained

    private void txfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUsuarioFocusGained
        if(txfUsuario.getForeground()==Color.red){
            Color og = new Color(51,51,51);
            txfUsuario.setForeground(og);
            txfUsuario.setText("");
        }
    }//GEN-LAST:event_txfUsuarioFocusGained

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestablecerContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txfContrasena1;
    private javax.swing.JTextField txfContrasena2;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
